### ISSUE TITLE
Suggestion for Avi in future videos

### ISSUE THREAD

**Issue by halfields** [learn-co-curriculum/rack-video-review-how-the-web-works-pt-2#1]
I like videos. Generally I learn well from videos. Avi needs to !)pack less information in his videos, and 2) slow down his presentation, (particularly when he is building a piece of server.) My learning curve is a normal bell curve. When the information rate is too slow, I get bored and learn less. There is a sweet spot, the median of the bell curve, where the information rate is just right and the learning rate is optimum. As the information rate is sped up past this point, I begin to miss concepts and learning drops off. When Avi gets sped up, as he does when he is building something, he is teaching in the far right hand tail of the curve, because I am overwhelmed. Sometimes I think Avi is just showing off. Earth to Avi: "We know you're good. Slow down, help us learn more. Particularly when there is an error. That is when Avi rushes the fastest, and that is the exact time when I would like him to teach the slowest. Because, guess what, I make errors, and I could learn a lot about fixing my errors if Avi would methodically explain what caused his code to break, the thinking process he goes through when he analyzes his mistake, and the corrections he comes up with. I know it takes time, so cut the amount of material you plan to cover, and maybe do 3 videos instead of 1.

**Comment by gj** [comment]
Passed this along! Thank you for the thoughtful feedback, @halfields.
