### ISSUE TITLE
Suggested Summary and Objectives

### ISSUE THREAD

**Issue by kyleblee** [learn-co-curriculum/rack-video-review-how-the-web-works-pt-2#3]
_Suggested Summary_
- In this lesson, we give an introduction to the conventions of a Rack / Sinatra project, the common file structure when setting up a Sinatra project, how we direct various requests using their routes / HTTP verbs in a dynamic application, and how the model-view-controller guides the structure of a project. 

_Suggested Objectives_
- Understand that _Rack_ is the foundation that _Sinatra_ and _Rails_ are built on.
- Set up a basic file structure that follows the conventions of a typical Sinatra app.
- Use _rackup_ and _shotgun_ to startup a local web server for interacting with your Rack or Sinatra application.
- Understand that a server can only handle one concurrent request at a time, but that complications are rare unless there are a large number of users.
- Explain the difference between _static web applications_ and _dynamic web applications_.
- Utilize the _shotgun_ gem so that you don’t have to stop and restart your local server each time you make a change in your files.
- Define what a _DSL_ (_domain-specific language_) is and why they are so useful to programmers.
- Define a _route_ and understand how to use URLs and HTTP verbs to determine which route responds to specific requests. 
- Create a new Sinatra app, using conventions for making/naming files and setting up the file structure.
- Understand the _config.ru_ file as the “bin” file of a web app—it is the first file that runs.
- Define a _controller_, _model_, and _view_ in the context of the _Model - View - Controller_ architecture and what specific job each has. 
- Create a _application_controller.rb_ file and write it with the run keyword in the _config.ru_ file to start the application.
- Use the _use_ keyword to mount all other controllers other than the one that you are going to run.
- Remember to add all new files to the _config/environment.rb_ file, so that your application can access them.
- Stay organized and place _model_, _view_, and _controller_ files in the app directory.
- Understand the general process that a Sinatra request goes through, from client through the controller to database / erb and back again.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for submitting your suggested Summary and Objectives.
